title: John R. Casey
description: Welcome to my homepage!
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
plugins:
  - jekyll-seo-tag
url: https://jrcasey.github.io
author: John Casey
twitter:
  username: kanakawicz
  card: summary
social:
  name: John Casey
  links:
    - https://twitter.com/kanakawicz
    - https://github.com/jrcasey
